name: Publish Docker image

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
  workflow_dispatch: {}

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract version from pyproject
        id: meta
        run: |
          VERSION=$(python - <<'PY'
import tomllib,sys
with open('pyproject.toml','rb') as f:
    d=tomllib.load(f)
print(d['project']['version'])
PY
)
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            altheasignals/boxofports:latest
            altheasignals/boxofports:${{ steps.meta.outputs.version }}
          cache-from: type=registry,ref=altheasignals/boxofports:buildcache
          cache-to: type=registry,ref=altheasignals/boxofports:buildcache,mode=max